name: grawlix
version: 0.0.0

category: Documentation
description: Grawlix lets you comment on Haskell documentation.
extra-source-files:
  - CHANGELOG.markdown
  - migrations/*.sql
  - README.markdown
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Comment on Haskell documentation.

dependencies:
  - base
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe

library:
  dependencies:
    - aeson
    - base16-bytestring
    - base64-bytestring
    - bytestring
    - Cabal
    - containers
    - contravariant
    - contravariant-extras
    - directory
    - exceptions
    - filepath
    - flow
    - hasql
    - hasql-migration
    - hasql-transaction
    - http-api-data
    - http-client
    - http-client-tls
    - http-types
    - optparse-generic
    - servant
    - servant-server
    - tagged
    - tar
    - template-haskell
    - text
    - wai
    - wai-extra
    - warp
    - yaml
    - zlib
  source-dirs: library

executables:

  grawlix-server:
    dependencies:
      - grawlix
    ghc-options:
      - -rtsopts
      - -threaded
    source-dirs: executables
    main: grawlix-server.hs

  grawlix-sync:
    dependencies:
      - grawlix
    ghc-options:
      - -rtsopts
      - -threaded
    source-dirs: executables
    main: grawlix-sync.hs
