resolver: lts-13.0

extra-deps:
  - butcher-1.3.2.1
  - multistate-0.8.0.1

  # https://github.com/lspitzner/brittany/pull/210
  - git: https://github.com/lspitzner/brittany
    commit: c4b696c4f654cc313d0abbb0647594b7deb3bd77

  # https://github.com/haskell/zlib/pull/20
  - git: https://github.com/tfausak/zlib
    commit: 0cb98dad2e6dc45d481072138de4dfb48c1c48df
